#!/usr/bin/env bash

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------------- Execution ----------------------------------

case "$1" in
  "on")
    echo-yellow "Activating Xdebug..."
    fin config set --env=local XDEBUG_ENABLED=1
    ;;
  "off")
    echo-yellow "Deactivating Xdebug..."
    fin config set --env=local XDEBUG_ENABLED=0
    ;;
  *)
    echo "Usage: $0 {on|off}"
    exit 1
esac

fin project start
fin exec php -v | grep -i xdebug

echo-green "DONE!"
